ServerName localhost

ProxyPreserveHost On
ProxyRequests Off
ProxyTimeout 300

<Location "/server-status">
    SetHandler server-status
    Require all granted
</Location>

ProxyPass        "/tomcat/"   "http://tomcat:8080/"
ProxyPassReverse "/tomcat/"   "http://tomcat:8080/"

ProxyPass        "/wildfly/"  "http://wildfly:8080/"
ProxyPassReverse "/wildfly/"  "http://wildfly:8080/"

ProxyPass        "/liberty/"  "http://liberty:9080/"
ProxyPassReverse "/liberty/"  "http://liberty:9080/"

ProxyPass        "/weblogic/" "http://weblogic:7001/"
ProxyPassReverse "/weblogic/" "http://weblogic:7001/"
